workspace = { members = [
    "display-interface-fsmc",
] }

[package]
name = "osc-counect-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embassy-stm32 = { version = "0.1.0", path = "./embassy/embassy-stm32", features = [ "defmt", "stm32f103vc", "unstable-pac", "memory-x", "time-driver-any" ]  }
embassy-sync = { version = "0.5.0", path = "./embassy/embassy-sync", features = ["defmt"] }
embassy-executor = { version = "0.5.0", path = "./embassy/embassy-executor", features = ["arch-cortex-m", "executor-thread", "defmt", "integrated-timers"] }
embassy-time = { version = "0.3.0", path = "./embassy/embassy-time", features = ["defmt", "defmt-timestamp-uptime", "tick-hz-32_768"] }
embassy-usb = { version = "0.1.0", path = "./embassy/embassy-usb", features = ["defmt"] }
embassy-futures = { version = "0.1.0", path = "./embassy/embassy-futures" }

defmt = "0.3"
defmt-rtt = "0.4"

panic-probe = { version = "0.3", features = ["print-defmt"] }
futures = { version = "0.3.17", default-features = false, features = ["async-await"] }
heapless = { version = "0.8", default-features = false }

cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.3"
cstr_core = "0.2.6"
display-interface = "0.4.1"
embedded-alloc = "0.5.1"
embedded-graphics = "0.7.1"
embedded-graphics-core = "0.3.3"
embedded-hal = "0.2.7"
format_no_std = "1.0.2"
fugit = "0.3.7"
ili9341 = "0.5.0"
nb = "1"

# Target side implementation of the RTT (Real-Time Transfer) I/O protocol
[dependencies.rtt-target]
version = "0.5.0"

[dependencies.panic-rtt-target]
version = "0.1.2"
features = ["cortex-m"]

[dependencies.display-interface-fsmc]
path = "display-interface-fsmc"

[dependencies.lvgl]
version = "0.6.2"
features = [
    "embedded_graphics", "unsafe_no_autoinit",
    "alloc", "lvgl_alloc"
]
default-features = false

[dependencies.lvgl-sys]
version = "0.6.2"
default-features = false

[profile.dev]
opt-level = 1
#opt-level = 0
debug = true
lto = true

[profile.release.package."*"]
#opt-level = 3
opt-level = "z"
debug = false
#lto = true
strip = false

[profile.release.package.lvgl-sys]
strip = false
opt-level = "z"
debug = false
#lto = true
