[package]
name = "osc-counect-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embassy-stm32 = { version = "0.1.0", path = "./embassy/embassy-stm32", features = [
    "defmt",
    "unstable-pac",
    "memory-x",
    "time-driver-any",
] }
embassy-sync = { version = "0.5.0", path = "./embassy/embassy-sync", features = [
    "defmt",
] }
embassy-executor = { version = "0.5.0", path = "./embassy/embassy-executor", features = [
    "arch-cortex-m",
    "executor-thread",
    "defmt",
    "integrated-timers",
] }
embassy-time = { version = "0.3.0", path = "./embassy/embassy-time", features = [
    "defmt",
    "defmt-timestamp-uptime",
    # "tick-hz-32_768",
    "tick-hz-1_000_000",
] }
embassy-usb = { version = "0.1.0", path = "./embassy/embassy-usb", features = [
    "defmt",
] }
embassy-usb-dfu = { version = "0.1.0", path = "./embassy/embassy-usb-dfu", features = [
    "dfu",
] }
# embassy-boot = { version = "0.2.0", path = "./embassy/embassy-boot", features = [
#     "defmt",
# ] }
# embassy-boot-stm32 = { version = "0.2.0", path = "./embassy/embassy-boot-stm32", features = [
#     "defmt",
# ] }
embassy-usb-driver = { version = "0.1.0", path = "./embassy/embassy-usb-driver" }
embassy-futures = { version = "0.1.0", path = "./embassy/embassy-futures" }
defmt = "0.3"
defmt-rtt = "0.4"

panic-probe = { version = "0.3", features = ["print-defmt"] }
futures = { version = "0.3.17", default-features = false, features = [
    "async-await",
] }
heapless = { version = "0.8", default-features = false }

cortex-m = { version = "0.7.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.3"
cstr_core = "0.2.6"
display-interface = "0.5.0"
embedded-alloc = "0.5.1"
embedded-graphics = "0.8.1"
embedded-graphics-core = "0.4.0"
embedded-hal = "1.0.0"
format_no_std = "1.0.2"
fugit = "0.3.7"
nb = "1"

[workspace]
members = ["tm1668", "display-interface-fsmc", "ili9327"]

[dependencies.ili9341]
path = "ili9327"
features = ["async"]

# Target side implementation of the RTT (Real-Time Transfer) I/O protocol
[dependencies.rtt-target]
version = "0.5.0"

[dependencies.panic-rtt-target]
version = "0.1.2"
features = ["cortex-m"]

[dependencies.display-interface-fsmc]
path = "display-interface-fsmc"
features = ["async"]

[dependencies.tm1668]
path = "tm1668"

[profile.dev]
opt-level = 0
#opt-level = 0
debug = true
lto = true

[profile.release]
#opt-level = 3
opt-level = "s"
debug = 2
lto = true
#strip = false

[features]
# default = ["stm32h743vi"]
default = ["stm32f103vc"]
stm32f103vc = ["embassy-stm32/stm32f103vc"]
stm32h743vi = ["embassy-stm32/stm32h743vi"]