[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32F103VC"

[build]
target = "thumbv7m-none-eabi"

[tasks.flash]
command = "openocd"
args = [
    "-f", "openocd.cfg",
]

[env]
# DEFMT_LOG = "info"
DEFMT_LOG = "trace"
