[alias]
simulator = "run --bin simulator --target x86_64-unknown-linux-gnu --features=simulator --no-default-features --release"
esp32c3 = "run --no-default-features --features=esp32c3,defmt --bin osc-esp32c3 --target=riscv32imc-unknown-none-elf"
stm32f103vc = "run --no-default-features --features=stm32f103vc,defmt --release --bin=osc-counect --target=thumbv7m-none-eabi"

[target.thumbv7em-none-eabi]
runner = "probe-rs run --chip STM32H743VITx"

[target.thumbv7m-none-eabi]
runner = "probe-rs run --chip STM32F103VC"

[target.'cfg(target_arch = "riscv32")']
runner = "espflash flash --monitor -L defmt"
rustflags = ["-C", "link-arg=-Tlinkall.x", "-C", "force-frame-pointers"]

[build]
# target = "thumbv7m-none-eabi"
# target = "thumbv7em-none-eabi"
target = "riscv32imc-unknown-none-elf"
# rustflags = ["-Z", "threads=8"]

[tasks.flash]
command = "openocd"
args = ["-f", "openocd.cfg"]

[env]
# DEFMT_LOG = "info"
DEFMT_LOG = "trace"
RUST_LOG = "info"

# [unstable]
# build-std = ["alloc", "core"]
