[target.thumbv7em-none-eabi]
runner = "probe-rs run --chip STM32H743VITx"

[target.thumbv7m-none-eabi]
runner = "probe-rs run --chip STM32F103VC"

[build]
target = "thumbv7m-none-eabi"
# target = "thumbv7em-none-eabi"

[tasks.flash]
command = "openocd"
args = ["-f", "openocd.cfg"]

[env]
# DEFMT_LOG = "info"
DEFMT_LOG = "trace"
RUST_LOG = "info"
